name: Tests
on: push
jobs:
  test-node-js:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [14, 16, 18]
    name: Node.js v${{ matrix.node-version }}
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: make node_modules
      - name: Run checks
        run: make check
      - name: Run tests
        run: make ci-test
